### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by guojin1211** [dormouse/Flask_Docs_ZhCn#29]
(flask_doc) root@tesra36:/home/guojin/pr/Flask_Docs_ZhCn# make html
正在运行 Sphinx v2.1.2

Configuration error:
\u914d\u7f6e\u6587\u4ef6\u4e2d\u6709\u7a0b\u5e8f\u4e0a\u7684\u9519\u8bef\uff1a

Traceback (most recent call last):
  File "/root/anaconda3/envs/flask_doc/lib/python3.8/site-packages/sphinx/config.py", line 361, in eval_config_file
    execfile_(filename, namespace)
  File "/root/anaconda3/envs/flask_doc/lib/python3.8/site-packages/sphinx/util/pycompat.py", line 86, in execfile_
    exec(code, _globals)
  File "/home/guojin/pr/Flask_Docs_ZhCn/conf.py", line 1, in <module>
    from pallets_sphinx_themes import get_version
ImportError: cannot import name 'get_version' from 'pallets_sphinx_themes' (/home/guojin/pr/Flask_Docs_ZhCn/pallets_sphinx_themes/__init__.py)

Makefile:19: recipe for target 'html' failed
make: *** [html] Error 2

您好，根据您README中的步骤来，报了这个错误，请问是什么原因呢？

**Comment by dormouse** [comment]
文档已更新，可以再试试。
